[colors]
[colors.primary]
background = '#000000'
foreground = '#ffffff'

# Normal colors
[colors.normal]
black = '#32344a'
red = '#f93e41'
green = '#68ed40'
yellow = '#fcce28'
blue = '#4ea5fc'
magenta = '#955dfc'
cyan = '#449dab'
white = '#787c99'

# Bright colors
[colors.bright]
black = '#777777'
red = '#ff7a93'
green = '#b9f27c'
yellow = '#ff9e64'
blue = '#7da6ff'
magenta = '#bb9af7'
cyan = '#0db9d7'
white = '#acb0d0'

[colors.selection]
background = '#7aa2f7'
